import os
import shutil
import urbs
from datetime import date


input_files = "base_scenario_full.xlsx"
input_dir = 'Input'
input_path = os.path.join(input_dir, input_files)

result_name = 'Base_scenario_2_weeks'
result_dir = urbs.prepare_result_directory(result_name)  # name + time stamp

#get year
#year = 2050
year = date.today().year

# copy input file to result directory
try:
    shutil.copytree(input_path, os.path.join(result_dir, input_dir))
except NotADirectoryError:
    shutil.copyfile(input_path, os.path.join(result_dir, input_files))
# copy run file to result directory
shutil.copy(__file__, result_dir)

# objective function
objective = 'cost'  # set either 'cost' or 'CO2' as objective

# Choose Solver (cplex, glpk, gurobi, ...)
solver = 'gurobi'

# simulation timesteps
(offset, length) = (0,1095)  # time step selection
timesteps = range(offset, offset+length+1)
dt = 8  # length of each time step (unit: hours)

# detailed reporting commodity/sitesd
report_tuples = [
    (2050, 'ALB', 'Elec'),
    (2050, 'AUT', 'Elec'),
    (2050, 'BEL', 'Elec'),
    (2050, 'BGR', 'Elec'),
    (2050, 'CHE', 'Elec'),
    (2050, 'CZE', 'Elec'),
    (2050, 'DEU', 'Elec'),
    (2050, 'DNK', 'Elec'),
    (2050, 'ESP', 'Elec'),
    (2050, 'EST', 'Elec'),
    (2050, 'FIN', 'Elec'),
    (2050, 'FRA', 'Elec'),
    (2050, 'GBR', 'Elec'),
    (2050, 'GRC', 'Elec'),
    (2050, 'HRV', 'Elec'),
    (2050, 'HUN', 'Elec'),
    (2050, 'IRL', 'Elec'),
    (2050, 'ITA', 'Elec'),
    (2050, 'LTU', 'Elec'),
    (2050, 'LUX', 'Elec'),
    (2050, 'LVA', 'Elec'),
    (2050, 'MKD', 'Elec'),
    (2050, 'MNE', 'Elec'),
    (2050, 'NLD', 'Elec'),
    (2050, 'NOR', 'Elec'),
    (2050, 'POL', 'Elec'),
    (2050, 'PRT', 'Elec'),
    (2050, 'ROU', 'Elec'),
    (2050, 'SRB', 'Elec'),
    (2050, 'SVK', 'Elec'),
    (2050, 'SVN', 'Elec'),
    (2050, 'SWE', 'Elec'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA',
      'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Elec'),
    (2050, 'ALB', 'Heat_Q1'),
    (2050, 'AUT', 'Heat_Q1'),
    (2050, 'BEL', 'Heat_Q1'),
    (2050, 'CHE', 'Heat_Q1'),
    (2050, 'BGR', 'Heat_Q1'),
    (2050, 'CZE', 'Heat_Q1'),
    (2050, 'DEU', 'Heat_Q1'),
    (2050, 'DNK', 'Heat_Q1'),
    (2050, 'ESP', 'Heat_Q1'),
    (2050, 'EST', 'Heat_Q1'),
    (2050, 'FIN', 'Heat_Q1'),
    (2050, 'FRA', 'Heat_Q1'),
    (2050, 'GBR', 'Heat_Q1'),
    (2050, 'GRC', 'Heat_Q1'),
    (2050, 'HRV', 'Heat_Q1'),
    (2050, 'HUN', 'Heat_Q1'),
    (2050, 'IRL', 'Heat_Q1'),
    (2050, 'ITA', 'Heat_Q1'),
    (2050, 'LTU', 'Heat_Q1'),
    (2050, 'LUX', 'Heat_Q1'),
    (2050, 'LVA', 'Heat_Q1'),
    (2050, 'MKD', 'Heat_Q1'),
    (2050, 'MNE', 'Heat_Q1'),
    (2050, 'NLD', 'Heat_Q1'),
    (2050, 'NOR', 'Heat_Q1'),
    (2050, 'POL', 'Heat_Q1'),
    (2050, 'PRT', 'Heat_Q1'),
    (2050, 'ROU', 'Heat_Q1'),
    (2050, 'SRB', 'Heat_Q1'),
    (2050, 'SVK', 'Heat_Q1'),
    (2050, 'SVN', 'Heat_Q1'),
    (2050, 'SWE', 'Heat_Q1'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Heat_Q1'),
    (2050, 'ALB', 'Heat_Q2'),
    (2050, 'AUT', 'Heat_Q2'),
    (2050, 'BEL', 'Heat_Q2'),
    (2050, 'CHE', 'Heat_Q2'),
    (2050, 'BGR', 'Heat_Q2'),
    (2050, 'CZE', 'Heat_Q2'),
    (2050, 'DEU', 'Heat_Q2'),
    (2050, 'DNK', 'Heat_Q2'),
    (2050, 'ESP', 'Heat_Q2'),
    (2050, 'EST', 'Heat_Q2'),
    (2050, 'FIN', 'Heat_Q2'),
    (2050, 'FRA', 'Heat_Q2'),
    (2050, 'GBR', 'Heat_Q2'),
    (2050, 'GRC', 'Heat_Q2'),
    (2050, 'HRV', 'Heat_Q2'),
    (2050, 'HUN', 'Heat_Q2'),
    (2050, 'IRL', 'Heat_Q2'),
    (2050, 'ITA', 'Heat_Q2'),
    (2050, 'LTU', 'Heat_Q2'),
    (2050, 'LUX', 'Heat_Q2'),
    (2050, 'LVA', 'Heat_Q2'),
    (2050, 'MKD', 'Heat_Q2'),
    (2050, 'MNE', 'Heat_Q2'),
    (2050, 'NLD', 'Heat_Q2'),
    (2050, 'NOR', 'Heat_Q2'),
    (2050, 'POL', 'Heat_Q2'),
    (2050, 'PRT', 'Heat_Q2'),
    (2050, 'ROU', 'Heat_Q2'),
    (2050, 'SRB', 'Heat_Q2'),
    (2050, 'SVK', 'Heat_Q2'),
    (2050, 'SVN', 'Heat_Q2'),
    (2050, 'SWE', 'Heat_Q2'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR','CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Heat_Q2'),
    (2050, 'ALB', 'Heat_Q3'),
    (2050, 'AUT', 'Heat_Q3'),
    (2050, 'BEL', 'Heat_Q3'),
    (2050, 'CHE', 'Heat_Q3'),
    (2050, 'BGR', 'Heat_Q3'),
    (2050, 'CZE', 'Heat_Q3'),
    (2050, 'DEU', 'Heat_Q3'),
    (2050, 'DNK', 'Heat_Q3'),
    (2050, 'ESP', 'Heat_Q3'),
    (2050, 'EST', 'Heat_Q3'),
    (2050, 'FIN', 'Heat_Q3'),
    (2050, 'FRA', 'Heat_Q3'),
    (2050, 'GBR', 'Heat_Q3'),
    (2050, 'GRC', 'Heat_Q3'),
    (2050, 'HRV', 'Heat_Q3'),
    (2050, 'HUN', 'Heat_Q3'),
    (2050, 'IRL', 'Heat_Q3'),
    (2050, 'ITA', 'Heat_Q3'),
    (2050, 'LTU', 'Heat_Q3'),
    (2050, 'LUX', 'Heat_Q3'),
    (2050, 'LVA', 'Heat_Q3'),
    (2050, 'MKD', 'Heat_Q3'),
    (2050, 'MNE', 'Heat_Q3'),
    (2050, 'NLD', 'Heat_Q3'),
    (2050, 'NOR', 'Heat_Q3'),
    (2050, 'POL', 'Heat_Q3'),
    (2050, 'PRT', 'Heat_Q3'),
    (2050, 'ROU', 'Heat_Q3'),
    (2050, 'SRB', 'Heat_Q3'),
    (2050, 'SVK', 'Heat_Q3'),
    (2050, 'SVN', 'Heat_Q3'),
    (2050, 'SWE', 'Heat_Q3'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Heat_Q3'),
    (2050, 'ALB', 'Heat_Q4'),
    (2050, 'AUT', 'Heat_Q4'),
    (2050, 'BEL', 'Heat_Q4'),
    (2050, 'CHE', 'Heat_Q4'),
    (2050, 'BGR', 'Heat_Q4'),
    (2050, 'CZE', 'Heat_Q4'),
    (2050, 'DEU', 'Heat_Q4'),
    (2050, 'DNK', 'Heat_Q4'),
    (2050, 'ESP', 'Heat_Q4'),
    (2050, 'EST', 'Heat_Q4'),
    (2050, 'FIN', 'Heat_Q4'),
    (2050, 'FRA', 'Heat_Q4'),
    (2050, 'GBR', 'Heat_Q4'),
    (2050, 'GRC', 'Heat_Q4'),
    (2050, 'HRV', 'Heat_Q4'),
    (2050, 'HUN', 'Heat_Q4'),
    (2050, 'IRL', 'Heat_Q4'),
    (2050, 'ITA', 'Heat_Q4'),
    (2050, 'LTU', 'Heat_Q4'),
    (2050, 'LUX', 'Heat_Q4'),
    (2050, 'LVA', 'Heat_Q4'),
    (2050, 'MKD', 'Heat_Q4'),
    (2050, 'MNE', 'Heat_Q4'),
    (2050, 'NLD', 'Heat_Q4'),
    (2050, 'NOR', 'Heat_Q4'),
    (2050, 'POL', 'Heat_Q4'),
    (2050, 'PRT', 'Heat_Q4'),
    (2050, 'ROU', 'Heat_Q4'),
    (2050, 'SRB', 'Heat_Q4'),
    (2050, 'SVK', 'Heat_Q4'),
    (2050, 'SVN', 'Heat_Q4'),
    (2050, 'SWE', 'Heat_Q4'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Heat_Q4'),
    (2050, 'ALB', 'HeatTokamak'),
    (2050, 'AUT', 'HeatTokamak'),
    (2050, 'BEL', 'HeatTokamak'),
    (2050, 'BGR', 'HeatTokamak'),
    (2050, 'CHE', 'HeatTokamak'),
    (2050, 'CZE', 'HeatTokamak'),
    (2050, 'DEU', 'HeatTokamak'),
    (2050, 'DNK', 'HeatTokamak'),
    (2050, 'ESP', 'HeatTokamak'),
    (2050, 'EST', 'HeatTokamak'),
    (2050, 'FIN', 'HeatTokamak'),
    (2050, 'FRA', 'HeatTokamak'),
    (2050, 'GBR', 'HeatTokamak'),
    (2050, 'GRC', 'HeatTokamak'),
    (2050, 'HRV', 'HeatTokamak'),
    (2050, 'HUN', 'HeatTokamak'),
    (2050, 'IRL', 'HeatTokamak'),
    (2050, 'ITA', 'HeatTokamak'),
    (2050, 'LTU', 'HeatTokamak'),
    (2050, 'LUX', 'HeatTokamak'),
    (2050, 'LVA', 'HeatTokamak'),
    (2050, 'MKD', 'HeatTokamak'),
    (2050, 'MNE', 'HeatTokamak'),
    (2050, 'NLD', 'HeatTokamak'),
    (2050, 'NOR', 'HeatTokamak'),
    (2050, 'POL', 'HeatTokamak'),
    (2050, 'PRT', 'HeatTokamak'),
    (2050, 'ROU', 'HeatTokamak'),
    (2050, 'SRB', 'HeatTokamak'),
    (2050, 'SVK', 'HeatTokamak'),
    (2050, 'SVN', 'HeatTokamak'),
    (2050, 'SWE', 'HeatTokamak'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'HeatTokamak'),
    (2050, 'ALB', 'HeatStellarator'),
    (2050, 'AUT', 'HeatStellarator'),
    (2050, 'BEL', 'HeatStellarator'),
    (2050, 'BGR', 'HeatStellarator'),
    (2050, 'CHE', 'HeatStellarator'),
    (2050, 'CZE', 'HeatStellarator'),
    (2050, 'DEU', 'HeatStellarator'),
    (2050, 'DNK', 'HeatStellarator'),
    (2050, 'ESP', 'HeatStellarator'),
    (2050, 'EST', 'HeatStellarator'),
    (2050, 'FIN', 'HeatStellarator'),
    (2050, 'FRA', 'HeatStellarator'),
    (2050, 'GBR', 'HeatStellarator'),
    (2050, 'GRC', 'HeatStellarator'),
    (2050, 'HRV', 'HeatStellarator'),
    (2050, 'HUN', 'HeatStellarator'),
    (2050, 'IRL', 'HeatStellarator'),
    (2050, 'ITA', 'HeatStellarator'),
    (2050, 'LTU', 'HeatStellarator'),
    (2050, 'LUX', 'HeatStellarator'),
    (2050, 'LVA', 'HeatStellarator'),
    (2050, 'MKD', 'HeatStellarator'),
    (2050, 'MNE', 'HeatStellarator'),
    (2050, 'NLD', 'HeatStellarator'),
    (2050, 'NOR', 'HeatStellarator'),
    (2050, 'POL', 'HeatStellarator'),
    (2050, 'PRT', 'HeatStellarator'),
    (2050, 'ROU', 'HeatStellarator'),
    (2050, 'SRB', 'HeatStellarator'),
    (2050, 'SVK', 'HeatStellarator'),
    (2050, 'SVN', 'HeatStellarator'),
    (2050, 'SWE', 'HeatStellarator'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'HeatStellarator'),
    (2050, 'ALB', 'CO2'),
    (2050, 'AUT', 'CO2'),
    (2050, 'BEL', 'CO2'),
    (2050, 'CHE', 'CO2'),
    (2050, 'BGR', 'CO2'),
    (2050, 'CZE', 'CO2'),
    (2050, 'DEU', 'CO2'),
    (2050, 'DNK', 'CO2'),
    (2050, 'ESP', 'CO2'),
    (2050, 'EST', 'CO2'),
    (2050, 'FIN', 'CO2'),
    (2050, 'FRA', 'CO2'),
    (2050, 'GBR', 'CO2'),
    (2050, 'GRC', 'CO2'),
    (2050, 'HRV', 'CO2'),
    (2050, 'HUN', 'CO2'),
    (2050, 'IRL', 'CO2'),
    (2050, 'ITA', 'CO2'),
    (2050, 'LTU', 'CO2'),
    (2050, 'LUX', 'CO2'),
    (2050, 'LVA', 'CO2'),
    (2050, 'MKD', 'CO2'),
    (2050, 'MNE', 'CO2'),
    (2050, 'NLD', 'CO2'),
    (2050, 'NOR', 'CO2'),
    (2050, 'POL', 'CO2'),
    (2050, 'PRT', 'CO2'),
    (2050, 'ROU', 'CO2'),
    (2050, 'SRB', 'CO2'),
    (2050, 'SVK', 'CO2'),
    (2050, 'SVN', 'CO2'),
    (2050, 'SWE', 'CO2'),
    (2050,
     ['ALB', 'AUT', 'BEL', 'BGR', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
      'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE',
      'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'CO2'),
    
]

# optional: define names for sites in report_tuples
#report_sites_name = { }
report_sites_name = {('ALB','AUT','BEL','BGR','CHE','CZE','DEU','DNK','ESP','EST','FIN','FRA','GBR','GRC','HRV','HUN','IRL','ITA',
            'LTU','LUX','LVA','MKD','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE'): 'All'}

# plotting commodities/sites
plot_tuples = [
    # (year, 'ALB', 'Elec'),
    # (year, 'AUT', 'Elec'),
    # (year, 'BEL', 'Elec'),
    # (year, 'BGR', 'Elec'),
    # (year, 'BIH', 'Elec'),
    # (year, 'CHE', 'Elec'),
    # (year, 'CZE', 'Elec'),
    # (year, 'DEU', 'Elec'),
    # (year, 'DNK', 'Elec'),
    # (year, 'ESP', 'Elec'),
    # (year, 'EST', 'Elec'),
    # (year, 'FIN', 'Elec'),
    # (year, 'FRA', 'Elec'),
    # (year, 'GBR', 'Elec'),
    # (year, 'GRC', 'Elec'),
    # (year, 'HRV', 'Elec'),
    # (year, 'HUN', 'Elec'),
    # (year, 'IRL', 'Elec'),
    # (year, 'ITA', 'Elec'),
    # (year, 'LTU', 'Elec'),
    # (year, 'LUX', 'Elec'),
    # (year, 'LVA', 'Elec'),
    # (year, 'MKD', 'Elec'),
    # (year, 'MNE', 'Elec'),
    # (year, 'NLD', 'Elec'),
    # (year, 'NOR', 'Elec'),
    # (year, 'POL', 'Elec'),
    # (year, 'PRT', 'Elec'),
    # (year, 'ROU', 'Elec'),
    # (year, 'SRB', 'Elec'),
    # (year, 'SVK', 'Elec'),
    # (year, 'SVN', 'Elec'),
    # (year, 'SWE', 'Elec'),
    # (year, ['ALB','AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV', 'HUN',
    #     'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'Elec'),
    # (year, 'ALB', 'H2'),
    # (year, 'AUT', 'H2'),
    # (year, 'BEL', 'H2'),
    # (year, 'BGR', 'H2'),
    # (year, 'BIH', 'H2'),
    # (year, 'CHE', 'H2'),
    # (year, 'CZE', 'H2'),
    # (year, 'DEU', 'H2'),
    # (year, 'DNK', 'H2'),
    # (year, 'ESP', 'H2'),
    # (year, 'EST', 'H2'),
    # (year, 'FIN', 'H2'),
    # (year, 'FRA', 'H2'),
    # (year, 'GBR', 'H2'),
    # (year, 'GRC', 'H2'),
    # (year, 'HRV', 'H2'),
    # (year, 'HUN', 'H2'),
    # (year, 'IRL', 'H2'),
    # (year, 'ITA', 'H2'),
    # (year, 'LTU', 'H2'),
    # (year, 'LUX', 'H2'),
    # (year, 'LVA', 'H2'),
    # (year, 'MKD', 'H2'),
    # (year, 'MNE', 'H2'),
    # (year, 'NLD', 'H2'),
    # (year, 'NOR', 'H2'),
    # (year, 'POL', 'H2'),
    # (year, 'PRT', 'H2'),
    # (year, 'ROU', 'H2'),
    # (year, 'SRB', 'H2'),
    # (year, 'SVK', 'H2'),
    # (year, 'SVN', 'H2'),
    # (year, 'SWE', 'H2'),
    # (year, ['ALB','AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV', 'HUN',
    #     'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'H2'),
    # (year, 'ALB', 'HeatTokamak'),
    # (year, 'AUT', 'HeatTokamak'),
    # (year, 'BEL', 'HeatTokamak'),
    # (year, 'BGR', 'HeatTokamak'),
    # (year, 'BIH', 'HeatTokamak'),
    # (year, 'CHE', 'HeatTokamak'),
    # (year, 'CZE', 'HeatTokamak'),
    # (year, 'DEU', 'HeatTokamak'),
    # (year, 'DNK', 'HeatTokamak'),
    # (year, 'ESP', 'HeatTokamak'),
    # (year, 'EST', 'HeatTokamak'),
    # (year, 'FIN', 'HeatTokamak'),
    # (year, 'FRA', 'HeatTokamak'),
    # (year, 'GBR', 'HeatTokamak'),
    # (year, 'GRC', 'HeatTokamak'),
    # (year, 'HRV', 'HeatTokamak'),
    # (year, 'HUN', 'HeatTokamak'),
    # (year, 'IRL', 'HeatTokamak'),
    # (year, 'ITA', 'HeatTokamak'),
    # (year, 'LTU', 'HeatTokamak'),
    # (year, 'LUX', 'HeatTokamak'),
    # (year, 'LVA', 'HeatTokamak'),
    # (year, 'MKD', 'HeatTokamak'),
    # (year, 'MNE', 'HeatTokamak'),
    # (year, 'NLD', 'HeatTokamak'),
    # (year, 'NOR', 'HeatTokamak'),
    # (year, 'POL', 'HeatTokamak'),
    # (year, 'PRT', 'HeatTokamak'),
    # (year, 'ROU', 'HeatTokamak'),
    # (year, 'SRB', 'HeatTokamak'),
    # (year, 'SVK', 'HeatTokamak'),
    # (year, 'SVN', 'HeatTokamak'),
    # (year, 'SWE', 'HeatTokamak'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV','HUN','IRL', 'ITA',
    #   'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN','SWE'], 'HeatTokamak'),
    # (year, 'ALB', 'HeatStellarator'),
    # (year, 'AUT', 'HeatStellarator'),
    # (year, 'BEL', 'HeatStellarator'),
    # (year, 'BGR', 'HeatStellarator'),
    # (year, 'BIH', 'HeatStellarator'),
    # (year, 'CHE', 'HeatStellarator'),
    # (year, 'CZE', 'HeatStellarator'),
    # (year, 'DEU', 'HeatStellarator'),
    # (year, 'DNK', 'HeatStellarator'),
    # (year, 'ESP', 'HeatStellarator'),
    # (year, 'EST', 'HeatStellarator'),
    # (year, 'FIN', 'HeatStellarator'),
    # (year, 'FRA', 'HeatStellarator'),
    # (year, 'GBR', 'HeatStellarator'),
    # (year, 'GRC', 'HeatStellarator'),
    # (year, 'HRV', 'HeatStellarator'),
    # (year, 'HUN', 'HeatStellarator'),
    # (year, 'IRL', 'HeatStellarator'),
    # (year, 'ITA', 'HeatStellarator'),
    # (year, 'LTU', 'HeatStellarator'),
    # (year, 'LUX', 'HeatStellarator'),
    # (year, 'LVA', 'HeatStellarator'),
    # (year, 'MKD', 'HeatStellarator'),
    # (year, 'MNE', 'HeatStellarator'),
    # (year, 'NLD', 'HeatStellarator'),
    # (year, 'NOR', 'HeatStellarator'),
    # (year, 'POL', 'HeatStellarator'),
    # (year, 'PRT', 'HeatStellarator'),
    # (year, 'ROU', 'HeatStellarator'),
    # (year, 'SRB', 'HeatStellarator'),
    # (year, 'SVK', 'HeatStellarator'),
    # (year, 'SVN', 'HeatStellarator'),
    # (year, 'SWE', 'HeatStellarator'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV','HUN','IRL', 'ITA',
    #  'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'], 'HeatStellarator'),
    # (year, 'ALB', 'CO2'),
    # (year, 'AUT', 'CO2'),
    # (year, 'BEL', 'CO2'),
    # (year, 'CHE', 'CO2'),
    # (year, 'BGR', 'CO2'),
    # (year, 'BIH', 'CO2'),
    # (year, 'CZE', 'CO2'),
    # (year, 'DEU', 'CO2'),
    # (year, 'DNK', 'CO2'),
    # (year, 'ESP', 'CO2'),
    # (year, 'EST', 'CO2'),
    # (year, 'FIN', 'CO2'),
    # (year, 'FRA', 'CO2'),
    # (year, 'GBR', 'CO2'),
    # (year, 'GRC', 'CO2'),
    # (year, 'HRV', 'CO2'),
    # (year, 'HUN', 'CO2'),
    # (year, 'IRL', 'CO2'),
    # (year, 'ITA', 'CO2'),
    # (year, 'LTU', 'CO2'),
    # (year, 'LUX', 'CO2'),
    # (year, 'LVA', 'CO2'),
    # (year, 'MKD', 'CO2'),
    # (year, 'MNE', 'CO2'),
    # (year, 'NLD', 'CO2'),
    # (year, 'NOR', 'CO2'),
    # (year, 'POL', 'CO2'),
    # (year, 'PRT', 'CO2'),
    # (year, 'ROU', 'CO2'),
    # (year, 'SRB', 'CO2'),
    # (year, 'SVK', 'CO2'),
    # (year, 'SVN', 'CO2'),
    # (year, 'SWE', 'CO2'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'CO2'),
    # (year, 'ALB', 'pt_car_pkm'),
    # (year, 'AUT', 'pt_car_pkm'),
    # (year, 'BEL', 'pt_car_pkm'),
    # (year, 'CHE', 'pt_car_pkm'),
    # (year, 'BGR', 'pt_car_pkm'),
    # (year, 'BIH', 'pt_car_pkm'),
    # (year, 'CZE', 'pt_car_pkm'),
    # (year, 'DEU', 'pt_car_pkm'),
    # (year, 'DNK', 'pt_car_pkm'),
    # (year, 'ESP', 'pt_car_pkm'),
    # (year, 'EST', 'pt_car_pkm'),
    # (year, 'FIN', 'pt_car_pkm'),
    # (year, 'FRA', 'pt_car_pkm'),
    # (year, 'GBR', 'pt_car_pkm'),
    # (year, 'GRC', 'pt_car_pkm'),
    # (year, 'HRV', 'pt_car_pkm'),
    # (year, 'HUN', 'pt_car_pkm'),
    # (year, 'IRL', 'pt_car_pkm'),
    # (year, 'ITA', 'pt_car_pkm'),
    # (year, 'LTU', 'pt_car_pkm'),
    # (year, 'LUX', 'pt_car_pkm'),
    # (year, 'LVA', 'pt_car_pkm'),
    # (year, 'MKD', 'pt_car_pkm'),
    # (year, 'MNE', 'pt_car_pkm'),
    # (year, 'NLD', 'pt_car_pkm'),
    # (year, 'NOR', 'pt_car_pkm'),
    # (year, 'POL', 'pt_car_pkm'),
    # (year, 'PRT', 'pt_car_pkm'),
    # (year, 'ROU', 'pt_car_pkm'),
    # (year, 'SRB', 'pt_car_pkm'),
    # (year, 'SVK', 'pt_car_pkm'),
    # (year, 'SVN', 'pt_car_pkm'),
    # (year, 'SWE', 'pt_car_pkm'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'pt_car_pkm'),
    # (year, 'ALB', 'pt_bus_pkm'),
    # (year, 'AUT', 'pt_bus_pkm'),
    # (year, 'BEL', 'pt_bus_pkm'),
    # (year, 'CHE', 'pt_bus_pkm'),
    # (year, 'BGR', 'pt_bus_pkm'),
    # (year, 'BIH', 'pt_bus_pkm'),
    # (year, 'CZE', 'pt_bus_pkm'),
    # (year, 'DEU', 'pt_bus_pkm'),
    # (year, 'DNK', 'pt_bus_pkm'),
    # (year, 'ESP', 'pt_bus_pkm'),
    # (year, 'EST', 'pt_bus_pkm'),
    # (year, 'FIN', 'pt_bus_pkm'),
    # (year, 'FRA', 'pt_bus_pkm'),
    # (year, 'GBR', 'pt_bus_pkm'),
    # (year, 'GRC', 'pt_bus_pkm'),
    # (year, 'HRV', 'pt_bus_pkm'),
    # (year, 'HUN', 'pt_bus_pkm'),
    # (year, 'IRL', 'pt_bus_pkm'),
    # (year, 'ITA', 'pt_bus_pkm'),
    # (year, 'LTU', 'pt_bus_pkm'),
    # (year, 'LUX', 'pt_bus_pkm'),
    # (year, 'LVA', 'pt_bus_pkm'),
    # (year, 'MKD', 'pt_bus_pkm'),
    # (year, 'MNE', 'pt_bus_pkm'),
    # (year, 'NLD', 'pt_bus_pkm'),
    # (year, 'NOR', 'pt_bus_pkm'),
    # (year, 'POL', 'pt_bus_pkm'),
    # (year, 'PRT', 'pt_bus_pkm'),
    # (year, 'ROU', 'pt_bus_pkm'),
    # (year, 'SRB', 'pt_bus_pkm'),
    # (year, 'SVK', 'pt_bus_pkm'),
    # (year, 'SVN', 'pt_bus_pkm'),
    # (year, 'SWE', 'pt_bus_pkm'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'pt_bus_pkm'),
    # (year, 'ALB', 'pt_rail_pkm'),
    # (year, 'AUT', 'pt_rail_pkm'),
    # (year, 'BEL', 'pt_rail_pkm'),
    # (year, 'CHE', 'pt_rail_pkm'),
    # (year, 'BGR', 'pt_rail_pkm'),
    # (year, 'BIH', 'pt_rail_pkm'),
    # (year, 'CZE', 'pt_rail_pkm'),
    # (year, 'DEU', 'pt_rail_pkm'),
    # (year, 'DNK', 'pt_rail_pkm'),
    # (year, 'ESP', 'pt_rail_pkm'),
    # (year, 'EST', 'pt_rail_pkm'),
    # (year, 'FIN', 'pt_rail_pkm'),
    # (year, 'FRA', 'pt_rail_pkm'),
    # (year, 'GBR', 'pt_rail_pkm'),
    # (year, 'GRC', 'pt_rail_pkm'),
    # (year, 'HRV', 'pt_rail_pkm'),
    # (year, 'HUN', 'pt_rail_pkm'),
    # (year, 'IRL', 'pt_rail_pkm'),
    # (year, 'ITA', 'pt_rail_pkm'),
    # (year, 'LTU', 'pt_rail_pkm'),
    # (year, 'LUX', 'pt_rail_pkm'),
    # (year, 'LVA', 'pt_rail_pkm'),
    # (year, 'MKD', 'pt_rail_pkm'),
    # (year, 'MNE', 'pt_rail_pkm'),
    # (year, 'NLD', 'pt_rail_pkm'),
    # (year, 'NOR', 'pt_rail_pkm'),
    # (year, 'POL', 'pt_rail_pkm'),
    # (year, 'PRT', 'pt_rail_pkm'),
    # (year, 'ROU', 'pt_rail_pkm'),
    # (year, 'SRB', 'pt_rail_pkm'),
    # (year, 'SVK', 'pt_rail_pkm'),
    # (year, 'SVN', 'pt_rail_pkm'),
    # (year, 'SWE', 'pt_rail_pkm'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'pt_rail_pkm'),
    # (year, 'ALB', 'ft_road_tkm'),
    # (year, 'AUT', 'ft_road_tkm'),
    # (year, 'BEL', 'ft_road_tkm'),
    # (year, 'CHE', 'ft_road_tkm'),
    # (year, 'BGR', 'ft_road_tkm'),
    # (year, 'BIH', 'ft_road_tkm'),
    # (year, 'CZE', 'ft_road_tkm'),
    # (year, 'DEU', 'ft_road_tkm'),
    # (year, 'DNK', 'ft_road_tkm'),
    # (year, 'ESP', 'ft_road_tkm'),
    # (year, 'EST', 'ft_road_tkm'),
    # (year, 'FIN', 'ft_road_tkm'),
    # (year, 'FRA', 'ft_road_tkm'),
    # (year, 'GBR', 'ft_road_tkm'),
    # (year, 'GRC', 'ft_road_tkm'),
    # (year, 'HRV', 'ft_road_tkm'),
    # (year, 'HUN', 'ft_road_tkm'),
    # (year, 'IRL', 'ft_road_tkm'),
    # (year, 'ITA', 'ft_road_tkm'),
    # (year, 'LTU', 'ft_road_tkm'),
    # (year, 'LUX', 'ft_road_tkm'),
    # (year, 'LVA', 'ft_road_tkm'),
    # (year, 'MKD', 'ft_road_tkm'),
    # (year, 'MNE', 'ft_road_tkm'),
    # (year, 'NLD', 'ft_road_tkm'),
    # (year, 'NOR', 'ft_road_tkm'),
    # (year, 'POL', 'ft_road_tkm'),
    # (year, 'PRT', 'ft_road_tkm'),
    # (year, 'ROU', 'ft_road_tkm'),
    # (year, 'SRB', 'ft_road_tkm'),
    # (year, 'SVK', 'ft_road_tkm'),
    # (year, 'SVN', 'ft_road_tkm'),
    # (year, 'SWE', 'ft_road_tkm'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'ft_road_tkm'),
    # (year, 'ALB', 'ft_railway_tkm'),
    # (year, 'AUT', 'ft_railway_tkm'),
    # (year, 'BEL', 'ft_railway_tkm'),
    # (year, 'CHE', 'ft_railway_tkm'),
    # (year, 'BGR', 'ft_railway_tkm'),
    # (year, 'BIH', 'ft_railway_tkm'),
    # (year, 'CZE', 'ft_railway_tkm'),
    # (year, 'DEU', 'ft_railway_tkm'),
    # (year, 'DNK', 'ft_railway_tkm'),
    # (year, 'ESP', 'ft_railway_tkm'),
    # (year, 'EST', 'ft_railway_tkm'),
    # (year, 'FIN', 'ft_railway_tkm'),
    # (year, 'FRA', 'ft_railway_tkm'),
    # (year, 'GBR', 'ft_railway_tkm'),
    # (year, 'GRC', 'ft_railway_tkm'),
    # (year, 'HRV', 'ft_railway_tkm'),
    # (year, 'HUN', 'ft_railway_tkm'),
    # (year, 'IRL', 'ft_railway_tkm'),
    # (year, 'ITA', 'ft_railway_tkm'),
    # (year, 'LTU', 'ft_railway_tkm'),
    # (year, 'LUX', 'ft_railway_tkm'),
    # (year, 'LVA', 'ft_railway_tkm'),
    # (year, 'MKD', 'ft_railway_tkm'),
    # (year, 'MNE', 'ft_railway_tkm'),
    # (year, 'NLD', 'ft_railway_tkm'),
    # (year, 'NOR', 'ft_railway_tkm'),
    # (year, 'POL', 'ft_railway_tkm'),
    # (year, 'PRT', 'ft_railway_tkm'),
    # (year, 'ROU', 'ft_railway_tkm'),
    # (year, 'SRB', 'ft_railway_tkm'),
    # (year, 'SVK', 'ft_railway_tkm'),
    # (year, 'SVN', 'ft_railway_tkm'),
    # (year, 'SWE', 'ft_railway_tkm'),
    # (year,
    #  ['ALB', 'AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV',
    #   'HUN',
    #   'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'],
    #  'ft_railway_tkm')
]
# optional: define names for sites in plot_tuples
plot_sites_name = {
    #('ALB','AUT', 'BEL', 'BGR', 'BIH', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HRV', 'HUN',
    # 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MKD', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'SRB', 'SVK', 'SVN', 'SWE'): 'All'
    }

# plotting timesteps
plot_periods = {
    #'all': timesteps[1:]
}

# add or change plot colors
my_colors = {
    # 'ALB': (230, 200, 200),
    # 'AUT': (200, 230, 200),
    # 'BEL': (200, 200, 230),
    # 'BGR': (230, 200, 200),
    # 'BIH': (200, 230, 200),
    # 'CHE': (200, 200, 230),
    # 'CZE': (230, 200, 200),
    # 'DEU': (200, 230, 200),
    # 'DNK': (200, 200, 230),
    # 'ESP': (200, 200, 230),
    # 'EST': (230, 200, 200),
    # 'FIN': (200, 230, 200),
    # 'FRA': (200, 200, 230),
    # 'GBR': (230, 200, 200),
    # 'GRC': (200, 230, 200),
    # 'HRV': (200, 200, 230),
    # 'HUN': (230, 200, 200),
    # 'IRL': (200, 230, 200),
    # 'ITA': (200, 200, 230),
    # 'KOS': (200, 200, 230),
    # 'LTU': (230, 200, 200),
    # 'LUX': (200, 230, 200),
    # 'LVA': (200, 200, 230),
    # 'MKD': (230, 200, 200),
    # 'MNE': (200, 230, 200),
    # 'NLD': (200, 200, 230),
    # 'NOR': (230, 200, 200),
    # 'POL': (200, 230, 200),
    # 'PRT': (200, 200, 230),
    # 'ROU': (200, 200, 230),
    # 'SRB': (230, 200, 200),
    # 'SVK': (200, 230, 200),
    # 'SVN': (200, 200, 230),
    # 'SWE': (200, 200, 230),
    }
for country, color in my_colors.items():
    urbs.COLORS[country] = color

# select scenarios to be run
scenarios = [
             urbs.scenario_base,
             # urbs.scenario_stock_prices,
             # urbs.scenario_co2_limit,
             # urbs.scenario_co2_tax_europe, #original urbs.scenario_co2_tax_north
             # urbs.scenario_no_dsm,
             # urbs.scenario_europe_process_caps, #original urbs.scenario_north_process_caps,
             # urbs.scenario_all_together
            ]

for scenario in scenarios:
    prob = urbs.run_scenario(input_path, solver, timesteps, scenario,
                             result_dir, dt, objective,
                             plot_tuples=plot_tuples,
                             plot_sites_name=plot_sites_name,
                             plot_periods=plot_periods,
                             report_tuples=report_tuples,
                             report_sites_name=report_sites_name)